Task/pce 84 implement products page
Osama671/pc-parts-e-commerce-site pull request #63
Opened 2024-06-19 01:51 UTC by Osama671

2024-06-19 13:26 UTC, georgevarghese185 requested changes

2024-06-19 13:33 UTC, georgevarghese185 commented on web/pages/Products.jsx
> +import './css/Products.css'
Aight, this looks like a good place for us to experiment with css modules.

https://vitejs.dev/guide/features#css-modules
https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/

2024-06-19 15:38 UTC, georgevarghese185 commented
Move `/components` to `/web` isntead of inside `/pages`

2024-06-25 04:19 UTC, uday-jangra commented
@Osama671 also, the lint check is failing.

2024-07-20 03:03 UTC, georgevarghese185 approved these changes

2024-07-21 22:37 UTC, merged